export const USER_ROLE = {
  CUSTOMER: 'Customer',
  MANAGER: 'Manager',
  SELLER: 'Seller',
  ADMIN: 'Admin',
};

export const INTERESTS = [
  { id: 1, name: 'Toán học', emoji: '📐' },
  { id: 2, name: 'Lập trình', emoji: '💻' },
  { id: 3, name: 'Hóa học', emoji: '🧪' },
  { id: 4, name: 'Vật lý', emoji: '⚛️' },
  { id: 5, name: 'Tiếng Anh', emoji: '🇬🇧' },
  { id: 6, name: 'Văn học', emoji: '📚' },
  { id: 7, name: 'Lịch sử', emoji: '🏛️' },
  { id: 8, name: 'Địa lý', emoji: '🌍' },
  { id: 9, name: 'Sinh học', emoji: '🧬' },
  { id: 10, name: 'Kinh tế', emoji: '💹' },
  { id: 11, name: 'Thiết kế đồ họa', emoji: '🎨' },
  { id: 12, name: 'Trí tuệ nhân tạo', emoji: '🤖' },
  { id: 13, name: 'Khoa học dữ liệu', emoji: '📊' },
  { id: 14, name: 'Tiếng Nhật', emoji: '🇯🇵' },
  { id: 15, name: 'Tiếng Hàn', emoji: '🇰🇷' },
  { id: 16, name: 'Âm nhạc', emoji: '🎶' },
  { id: 17, name: 'Nhiếp ảnh', emoji: '📷' },
  { id: 18, name: 'Kỹ thuật cơ khí', emoji: '⚙️' },
  { id: 19, name: 'Y học', emoji: '🩺' },
  { id: 20, name: 'Luật', emoji: '⚖️' },
  { id: 21, name: 'Marketing', emoji: '📈' },
  { id: 22, name: 'Kiến trúc', emoji: '🏛️' },
  { id: 23, name: 'Thiên văn học', emoji: '🌌' },
  { id: 24, name: 'Tâm lý học', emoji: '🧠' },
  { id: 25, name: 'Viết lách', emoji: '✍️' },
];
